In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

![1_QUOj_W3-DPeW7oBRgq2Iig.png](attachment:1_QUOj_W3-DPeW7oBRgq2Iig.png)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(r"E:\Data\iris.csv")

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df=df.drop("species",axis=1)

In [ ]:
df.shape

(150, 4)

In [ ]:
cov_mat=df.cov()

In [ ]:
cov_mat.values

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [ ]:
eigen_val,eigen_vector=np.linalg.eig(cov_mat.values)

In [ ]:
eigen_vector

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [ ]:
eigen_val

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [ ]:
a=eigen_vector[:,:3]
a.shape

(4, 3)

In [ ]:
a

array([[ 0.36138659, -0.65658877, -0.58202985],
       [-0.08452251, -0.73016143,  0.59791083],
       [ 0.85667061,  0.17337266,  0.07623608],
       [ 0.3582892 ,  0.07548102,  0.54583143]])

In [ ]:
a.shape

(4, 3)

In [ ]:
d=np.dot(df,a)

In [ ]:
d.shape

(150, 3)

In [ ]:
from sklearn.decomposition import PCA


In [ ]:
algo=PCA(n_components=3)

In [ ]:
algo.fit(df)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
df1=algo.transform(df)

In [ ]:
df1.shape

(150, 3)

In [ ]:
algo.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261])

In [ ]:
algo1=PCA(0.95)
algo1.fit(df)


PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
algo1.n_components_

2